### ISSUE TITLE
Legal move generation

### ISSUE THREAD

**Issue by mikebind** [dbqpdb/RLM#21]
Given a board and game state, the set of possible legal moves needs to be generated.  This is necessary both for validating user moves and for creating a list of moves RLM players can select from

**Comment by dbqpdb** [comment]
Subtasks include:
- each piece needs to know how it can move / capture
- the king needs to be able to recognize when he is in check
- pieces should report their views of the board to the king
- the king compiles the moves, and issues his order from among the moves that do not put/leave him in check
- special cases
  - castling
    - k/q side castling
    - blocked if castling through line of attack
    - can't castle twice
    - can't castle if either piece's been moved before
  - en passant
  - pawn promotion
